spring.application.name=NewGooglDocs

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

spring.devtools.livereload.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=TRACE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.jwt.secret-key=${JWT_SECRET}
spring.security.jwt.expiration=86400000